//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.TPC_Comm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="TPC_Comm.CommMdmWS")]
    public interface CommMdmWS {
        
        // CODEGEN: 命名空間  的元素名稱  XMLContent 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/CommMdmWS/SendMessageRequest", ReplyAction="http://ws/CommMdmWS/SendMessageResponse")]
        WindowsFormsApplication2.TPC_Comm.SendMessageResponse SendMessage(WindowsFormsApplication2.TPC_Comm.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/CommMdmWS/SendMessageRequest", ReplyAction="http://ws/CommMdmWS/SendMessageResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.TPC_Comm.SendMessageResponse> SendMessageAsync(WindowsFormsApplication2.TPC_Comm.SendMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://ws/", Order=0)]
        public WindowsFormsApplication2.TPC_Comm.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(WindowsFormsApplication2.TPC_Comm.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XMLContent;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string XMLContent) {
            this.XMLContent = XMLContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://ws/", Order=0)]
        public WindowsFormsApplication2.TPC_Comm.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(WindowsFormsApplication2.TPC_Comm.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommMdmWSChannel : WindowsFormsApplication2.TPC_Comm.CommMdmWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommMdmWSClient : System.ServiceModel.ClientBase<WindowsFormsApplication2.TPC_Comm.CommMdmWS>, WindowsFormsApplication2.TPC_Comm.CommMdmWS {
        
        public CommMdmWSClient() {
        }
        
        public CommMdmWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommMdmWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommMdmWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommMdmWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication2.TPC_Comm.SendMessageResponse WindowsFormsApplication2.TPC_Comm.CommMdmWS.SendMessage(WindowsFormsApplication2.TPC_Comm.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public string SendMessage(string XMLContent) {
            WindowsFormsApplication2.TPC_Comm.SendMessageRequest inValue = new WindowsFormsApplication2.TPC_Comm.SendMessageRequest();
            inValue.Body = new WindowsFormsApplication2.TPC_Comm.SendMessageRequestBody();
            inValue.Body.XMLContent = XMLContent;
            WindowsFormsApplication2.TPC_Comm.SendMessageResponse retVal = ((WindowsFormsApplication2.TPC_Comm.CommMdmWS)(this)).SendMessage(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication2.TPC_Comm.SendMessageResponse> WindowsFormsApplication2.TPC_Comm.CommMdmWS.SendMessageAsync(WindowsFormsApplication2.TPC_Comm.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.TPC_Comm.SendMessageResponse> SendMessageAsync(string XMLContent) {
            WindowsFormsApplication2.TPC_Comm.SendMessageRequest inValue = new WindowsFormsApplication2.TPC_Comm.SendMessageRequest();
            inValue.Body = new WindowsFormsApplication2.TPC_Comm.SendMessageRequestBody();
            inValue.Body.XMLContent = XMLContent;
            return ((WindowsFormsApplication2.TPC_Comm.CommMdmWS)(this)).SendMessageAsync(inValue);
        }
    }
}
